name: CI pipeline with Cypress and Allure Grouping
on:
  push:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallel-job: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check for Cache
        id: cache-miss
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.parallel-job }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.parallel-job }}

      - name: Install dependencies
        if: steps.cache-miss.outputs.cache-hit != 'true' # Only install if cache was not found
        run: npm install

      - name: Verify Cypress Installation
        run: npx cypress verify

      - name: Run Cypress Tests in Parallel with Allure
        uses: cypress-io/github-action@v6
        with:
          config: video=false
          parallel: true
          group: "group-${{ matrix.parallel-job }}"
          command: "npx cypress run --env allure=true"
        env:
          CYPRESS_ALLURE_GROUP: "group-${{ matrix.parallel-job }}"
          CYPRESS_ALLURE_RESULT_PATH: "./allure-results"

  generate-allure-reprot:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Allure CommandLine
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate --single-report ./allure-results --cleaen -o ./allure-report

      - name: Deploy Allure Report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: allure-history

    # - name: Load test report history
    #     uses: actions/checkout@v4
    #     continue-on-error: true
    #     with:
    #       ref: gh-pages
    #       path: gh-pages

    #   - name: Allure Report with history
    #     uses: simple-elf/allure-report-action@v1.9
    #     id: allure-report
    #     with:
    #       allure_results: allure-results
    #       gh_pages: gh-pages
    #       allure_report: allure-report
    #       allure_history: allure-history

    #   - name: GitHub Pages action
    #     uses: peaceiris/actions-gh-pages@v4
    #     with:
    #       personal_token: ${{ secrets.PERSONAL_TOKEN }}
    #       publish_dir: allure-history

  # cypress-run:
  # runs-on: ubuntu-22.04
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Set up node
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 20

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Cypress run dependency
  #     uses: cypress-io/github-action@v6
  #     with:
  #       runTests: false

  #   - name: Run e2e test
  #     uses: cypress-io/github-action@v6
  #     with:
  #       browser: chrome
  #       build: npm run build
  #       start: npm run start

  #   - name: Load test report history
  #     uses: actions/checkout@v4
  #     continue-on-error: true
  #     with:
  #       ref: gh-pages
  #       path: gh-pages

  #   - name: Allure Report with history
  #     uses: simple-elf/allure-report-action@v1.9
  #     id: allure-report
  #     with:
  #       allure_results: allure-results
  #       gh_pages: gh-pages
  #       allure_report: allure-report
  #       allure_history: allure-history

  #   - name: GitHub Pages action
  #     uses: peaceiris/actions-gh-pages@v4
  #     with:
  #       personal_token: ${{ secrets.PERSONAL_TOKEN }}
  #       publish_dir: allure-history
