name: Cypress E2E Tests
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress e2e tests
        run: npx cypress run
